/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snake */

#ifndef _Included_snake
#define _Included_snake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snake
 * Method:    getInput
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_snake_getInput
  (JNIEnv *, jclass);

/*
 * Class:     snake
 * Method:    getInputUp
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_snake_getInputUp
  (JNIEnv *, jclass);

/*
 * Class:     snake
 * Method:    getInputDown
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_snake_getInputDown
  (JNIEnv *, jclass);

/*
 * Class:     snake
 * Method:    getInputLeft
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_snake_getInputLeft
  (JNIEnv *, jclass);

/*
 * Class:     snake
 * Method:    getInputRight
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_snake_getInputRight
  (JNIEnv *, jclass);

/*
 * Class:     snake
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_snake_clearScreen
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
